ame: RestartOnEmpty
main: uk.asheiou.restartonempty.RestartOnEmpty
version: ${project.version}
author: Asheiou
api-version: 1.18
website: https://mc.asheiou.uk
description: >
             Allows you to set your server to restart on empty.
commands:
  restartonempty:
    aliases: [roe, ronempty]
    description: Set the server to restart on empty.
    usage: /<command> [true/false/status]
    permission: restartonempty.use
    permission-message: You don't have restartonempty.use.

permissions:
  restartonempty.use:
    description: Allows use of the plugin
    default: op
        